services:
  # 共享 PostgreSQL 数据库
  db:
    image: postgres:14
    container_name: postgres_db_shared
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev_network

  # Django 后端
  backend_dev1:
    build:
      context: /home/zgcc/project/packager/backend
      dockerfile: Dockerfile
    container_name: django_backend_zgcc
    environment:
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - dev_network
    volumes:
      - /home/zgcc/project/packager/backend:/app

  # Vue3 前端
  frontend_dev1:
    build:
      context: /home/zgcc/project/packager/frontend
      dockerfile: Dockerfile
    container_name: vue_frontend_zgcc
    depends_on:
      - backend_dev1
    networks:
      - dev_network
    volumes:
      - /home/zgcc/project/packager/frontend:/app

volumes:
  db_data:

networks:
  dev_network:
    name: dev_network
    driver: bridge
    external: true
