# Generated by Django 4.2.11 on 2025-04-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packager.freightplan'),
        ),
        migrations.AddField(
            model_name='freightplan',
            name='title',
            field=models.CharField(default='empty', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='freightplan',
            name='destination',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='freightplan',
            name='raw_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
