# Generated by Django 4.2.11 on 2025-04-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
